// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThreeQuestionsTxtFileMsg.proto

public final class ThreeQuestionsTxtFileProtos {
  private ThreeQuestionsTxtFileProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ThreeQuestionsTxtFileMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ThreeQuestionsTxtFileMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string question1 = 1;</code>
     * @return Whether the question1 field is set.
     */
    boolean hasQuestion1();
    /**
     * <code>required string question1 = 1;</code>
     * @return The question1.
     */
    String getQuestion1();
    /**
     * <code>required string question1 = 1;</code>
     * @return The bytes for question1.
     */
    com.google.protobuf.ByteString
        getQuestion1Bytes();

    /**
     * <code>required string question2 = 2;</code>
     * @return Whether the question2 field is set.
     */
    boolean hasQuestion2();
    /**
     * <code>required string question2 = 2;</code>
     * @return The question2.
     */
    String getQuestion2();
    /**
     * <code>required string question2 = 2;</code>
     * @return The bytes for question2.
     */
    com.google.protobuf.ByteString
        getQuestion2Bytes();

    /**
     * <code>required string question3 = 3;</code>
     * @return Whether the question3 field is set.
     */
    boolean hasQuestion3();
    /**
     * <code>required string question3 = 3;</code>
     * @return The question3.
     */
    String getQuestion3();
    /**
     * <code>required string question3 = 3;</code>
     * @return The bytes for question3.
     */
    com.google.protobuf.ByteString
        getQuestion3Bytes();

    /**
     * <code>required string encryptedKey1 = 4;</code>
     * @return Whether the encryptedKey1 field is set.
     */
    boolean hasEncryptedKey1();
    /**
     * <code>required string encryptedKey1 = 4;</code>
     * @return The encryptedKey1.
     */
    String getEncryptedKey1();
    /**
     * <code>required string encryptedKey1 = 4;</code>
     * @return The bytes for encryptedKey1.
     */
    com.google.protobuf.ByteString
        getEncryptedKey1Bytes();

    /**
     * <code>required string encryptedKey2 = 5;</code>
     * @return Whether the encryptedKey2 field is set.
     */
    boolean hasEncryptedKey2();
    /**
     * <code>required string encryptedKey2 = 5;</code>
     * @return The encryptedKey2.
     */
    String getEncryptedKey2();
    /**
     * <code>required string encryptedKey2 = 5;</code>
     * @return The bytes for encryptedKey2.
     */
    com.google.protobuf.ByteString
        getEncryptedKey2Bytes();

    /**
     * <code>required string encryptedKey3 = 6;</code>
     * @return Whether the encryptedKey3 field is set.
     */
    boolean hasEncryptedKey3();
    /**
     * <code>required string encryptedKey3 = 6;</code>
     * @return The encryptedKey3.
     */
    String getEncryptedKey3();
    /**
     * <code>required string encryptedKey3 = 6;</code>
     * @return The bytes for encryptedKey3.
     */
    com.google.protobuf.ByteString
        getEncryptedKey3Bytes();

    /**
     * <code>required string encryptedContent = 7;</code>
     * @return Whether the encryptedContent field is set.
     */
    boolean hasEncryptedContent();
    /**
     * <code>required string encryptedContent = 7;</code>
     * @return The encryptedContent.
     */
    String getEncryptedContent();
    /**
     * <code>required string encryptedContent = 7;</code>
     * @return The bytes for encryptedContent.
     */
    com.google.protobuf.ByteString
        getEncryptedContentBytes();
  }
  /**
   * Protobuf type {@code ThreeQuestionsTxtFileMsg}
   */
  public static final class ThreeQuestionsTxtFileMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ThreeQuestionsTxtFileMsg)
      ThreeQuestionsTxtFileMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ThreeQuestionsTxtFileMsg.newBuilder() to construct.
    private ThreeQuestionsTxtFileMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ThreeQuestionsTxtFileMsg() {
      question1_ = "";
      question2_ = "";
      question3_ = "";
      encryptedKey1_ = "";
      encryptedKey2_ = "";
      encryptedKey3_ = "";
      encryptedContent_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ThreeQuestionsTxtFileMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ThreeQuestionsTxtFileMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              question1_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              question2_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              question3_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              encryptedKey1_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              encryptedKey2_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              encryptedKey3_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              encryptedContent_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ThreeQuestionsTxtFileProtos.internal_static_ThreeQuestionsTxtFileMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ThreeQuestionsTxtFileProtos.internal_static_ThreeQuestionsTxtFileMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ThreeQuestionsTxtFileMsg.class, Builder.class);
    }

    private int bitField0_;
    public static final int QUESTION1_FIELD_NUMBER = 1;
    private volatile Object question1_;
    /**
     * <code>required string question1 = 1;</code>
     * @return Whether the question1 field is set.
     */
    @Override
    public boolean hasQuestion1() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string question1 = 1;</code>
     * @return The question1.
     */
    @Override
    public String getQuestion1() {
      Object ref = question1_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          question1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string question1 = 1;</code>
     * @return The bytes for question1.
     */
    @Override
    public com.google.protobuf.ByteString
        getQuestion1Bytes() {
      Object ref = question1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        question1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUESTION2_FIELD_NUMBER = 2;
    private volatile Object question2_;
    /**
     * <code>required string question2 = 2;</code>
     * @return Whether the question2 field is set.
     */
    @Override
    public boolean hasQuestion2() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string question2 = 2;</code>
     * @return The question2.
     */
    @Override
    public String getQuestion2() {
      Object ref = question2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          question2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string question2 = 2;</code>
     * @return The bytes for question2.
     */
    @Override
    public com.google.protobuf.ByteString
        getQuestion2Bytes() {
      Object ref = question2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        question2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUESTION3_FIELD_NUMBER = 3;
    private volatile Object question3_;
    /**
     * <code>required string question3 = 3;</code>
     * @return Whether the question3 field is set.
     */
    @Override
    public boolean hasQuestion3() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string question3 = 3;</code>
     * @return The question3.
     */
    @Override
    public String getQuestion3() {
      Object ref = question3_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          question3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string question3 = 3;</code>
     * @return The bytes for question3.
     */
    @Override
    public com.google.protobuf.ByteString
        getQuestion3Bytes() {
      Object ref = question3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        question3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTEDKEY1_FIELD_NUMBER = 4;
    private volatile Object encryptedKey1_;
    /**
     * <code>required string encryptedKey1 = 4;</code>
     * @return Whether the encryptedKey1 field is set.
     */
    @Override
    public boolean hasEncryptedKey1() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string encryptedKey1 = 4;</code>
     * @return The encryptedKey1.
     */
    @Override
    public String getEncryptedKey1() {
      Object ref = encryptedKey1_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encryptedKey1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string encryptedKey1 = 4;</code>
     * @return The bytes for encryptedKey1.
     */
    @Override
    public com.google.protobuf.ByteString
        getEncryptedKey1Bytes() {
      Object ref = encryptedKey1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        encryptedKey1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTEDKEY2_FIELD_NUMBER = 5;
    private volatile Object encryptedKey2_;
    /**
     * <code>required string encryptedKey2 = 5;</code>
     * @return Whether the encryptedKey2 field is set.
     */
    @Override
    public boolean hasEncryptedKey2() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string encryptedKey2 = 5;</code>
     * @return The encryptedKey2.
     */
    @Override
    public String getEncryptedKey2() {
      Object ref = encryptedKey2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encryptedKey2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string encryptedKey2 = 5;</code>
     * @return The bytes for encryptedKey2.
     */
    @Override
    public com.google.protobuf.ByteString
        getEncryptedKey2Bytes() {
      Object ref = encryptedKey2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        encryptedKey2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTEDKEY3_FIELD_NUMBER = 6;
    private volatile Object encryptedKey3_;
    /**
     * <code>required string encryptedKey3 = 6;</code>
     * @return Whether the encryptedKey3 field is set.
     */
    @Override
    public boolean hasEncryptedKey3() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string encryptedKey3 = 6;</code>
     * @return The encryptedKey3.
     */
    @Override
    public String getEncryptedKey3() {
      Object ref = encryptedKey3_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encryptedKey3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string encryptedKey3 = 6;</code>
     * @return The bytes for encryptedKey3.
     */
    @Override
    public com.google.protobuf.ByteString
        getEncryptedKey3Bytes() {
      Object ref = encryptedKey3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        encryptedKey3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPTEDCONTENT_FIELD_NUMBER = 7;
    private volatile Object encryptedContent_;
    /**
     * <code>required string encryptedContent = 7;</code>
     * @return Whether the encryptedContent field is set.
     */
    @Override
    public boolean hasEncryptedContent() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required string encryptedContent = 7;</code>
     * @return The encryptedContent.
     */
    @Override
    public String getEncryptedContent() {
      Object ref = encryptedContent_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encryptedContent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string encryptedContent = 7;</code>
     * @return The bytes for encryptedContent.
     */
    @Override
    public com.google.protobuf.ByteString
        getEncryptedContentBytes() {
      Object ref = encryptedContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        encryptedContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasQuestion1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuestion2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuestion3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptedKey1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptedKey2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptedKey3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptedContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, question1_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, question2_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, question3_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, encryptedKey1_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, encryptedKey2_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, encryptedKey3_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, encryptedContent_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, question1_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, question2_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, question3_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, encryptedKey1_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, encryptedKey2_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, encryptedKey3_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, encryptedContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ThreeQuestionsTxtFileMsg)) {
        return super.equals(obj);
      }
      ThreeQuestionsTxtFileMsg other = (ThreeQuestionsTxtFileMsg) obj;

      if (hasQuestion1() != other.hasQuestion1()) return false;
      if (hasQuestion1()) {
        if (!getQuestion1()
            .equals(other.getQuestion1())) return false;
      }
      if (hasQuestion2() != other.hasQuestion2()) return false;
      if (hasQuestion2()) {
        if (!getQuestion2()
            .equals(other.getQuestion2())) return false;
      }
      if (hasQuestion3() != other.hasQuestion3()) return false;
      if (hasQuestion3()) {
        if (!getQuestion3()
            .equals(other.getQuestion3())) return false;
      }
      if (hasEncryptedKey1() != other.hasEncryptedKey1()) return false;
      if (hasEncryptedKey1()) {
        if (!getEncryptedKey1()
            .equals(other.getEncryptedKey1())) return false;
      }
      if (hasEncryptedKey2() != other.hasEncryptedKey2()) return false;
      if (hasEncryptedKey2()) {
        if (!getEncryptedKey2()
            .equals(other.getEncryptedKey2())) return false;
      }
      if (hasEncryptedKey3() != other.hasEncryptedKey3()) return false;
      if (hasEncryptedKey3()) {
        if (!getEncryptedKey3()
            .equals(other.getEncryptedKey3())) return false;
      }
      if (hasEncryptedContent() != other.hasEncryptedContent()) return false;
      if (hasEncryptedContent()) {
        if (!getEncryptedContent()
            .equals(other.getEncryptedContent())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasQuestion1()) {
        hash = (37 * hash) + QUESTION1_FIELD_NUMBER;
        hash = (53 * hash) + getQuestion1().hashCode();
      }
      if (hasQuestion2()) {
        hash = (37 * hash) + QUESTION2_FIELD_NUMBER;
        hash = (53 * hash) + getQuestion2().hashCode();
      }
      if (hasQuestion3()) {
        hash = (37 * hash) + QUESTION3_FIELD_NUMBER;
        hash = (53 * hash) + getQuestion3().hashCode();
      }
      if (hasEncryptedKey1()) {
        hash = (37 * hash) + ENCRYPTEDKEY1_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedKey1().hashCode();
      }
      if (hasEncryptedKey2()) {
        hash = (37 * hash) + ENCRYPTEDKEY2_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedKey2().hashCode();
      }
      if (hasEncryptedKey3()) {
        hash = (37 * hash) + ENCRYPTEDKEY3_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedKey3().hashCode();
      }
      if (hasEncryptedContent()) {
        hash = (37 * hash) + ENCRYPTEDCONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ThreeQuestionsTxtFileMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ThreeQuestionsTxtFileMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ThreeQuestionsTxtFileMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ThreeQuestionsTxtFileMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ThreeQuestionsTxtFileMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ThreeQuestionsTxtFileMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ThreeQuestionsTxtFileMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ThreeQuestionsTxtFileMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ThreeQuestionsTxtFileMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ThreeQuestionsTxtFileMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ThreeQuestionsTxtFileMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ThreeQuestionsTxtFileMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ThreeQuestionsTxtFileMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ThreeQuestionsTxtFileMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ThreeQuestionsTxtFileMsg)
        ThreeQuestionsTxtFileMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ThreeQuestionsTxtFileProtos.internal_static_ThreeQuestionsTxtFileMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ThreeQuestionsTxtFileProtos.internal_static_ThreeQuestionsTxtFileMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ThreeQuestionsTxtFileMsg.class, Builder.class);
      }

      // Construct using ThreeQuestionsTxtFileProtos.ThreeQuestionsTxtFileMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        question1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        question2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        question3_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        encryptedKey1_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        encryptedKey2_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        encryptedKey3_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        encryptedContent_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ThreeQuestionsTxtFileProtos.internal_static_ThreeQuestionsTxtFileMsg_descriptor;
      }

      @Override
      public ThreeQuestionsTxtFileMsg getDefaultInstanceForType() {
        return ThreeQuestionsTxtFileMsg.getDefaultInstance();
      }

      @Override
      public ThreeQuestionsTxtFileMsg build() {
        ThreeQuestionsTxtFileMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ThreeQuestionsTxtFileMsg buildPartial() {
        ThreeQuestionsTxtFileMsg result = new ThreeQuestionsTxtFileMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.question1_ = question1_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.question2_ = question2_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.question3_ = question3_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.encryptedKey1_ = encryptedKey1_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.encryptedKey2_ = encryptedKey2_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.encryptedKey3_ = encryptedKey3_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.encryptedContent_ = encryptedContent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ThreeQuestionsTxtFileMsg) {
          return mergeFrom((ThreeQuestionsTxtFileMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ThreeQuestionsTxtFileMsg other) {
        if (other == ThreeQuestionsTxtFileMsg.getDefaultInstance()) return this;
        if (other.hasQuestion1()) {
          bitField0_ |= 0x00000001;
          question1_ = other.question1_;
          onChanged();
        }
        if (other.hasQuestion2()) {
          bitField0_ |= 0x00000002;
          question2_ = other.question2_;
          onChanged();
        }
        if (other.hasQuestion3()) {
          bitField0_ |= 0x00000004;
          question3_ = other.question3_;
          onChanged();
        }
        if (other.hasEncryptedKey1()) {
          bitField0_ |= 0x00000008;
          encryptedKey1_ = other.encryptedKey1_;
          onChanged();
        }
        if (other.hasEncryptedKey2()) {
          bitField0_ |= 0x00000010;
          encryptedKey2_ = other.encryptedKey2_;
          onChanged();
        }
        if (other.hasEncryptedKey3()) {
          bitField0_ |= 0x00000020;
          encryptedKey3_ = other.encryptedKey3_;
          onChanged();
        }
        if (other.hasEncryptedContent()) {
          bitField0_ |= 0x00000040;
          encryptedContent_ = other.encryptedContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasQuestion1()) {
          return false;
        }
        if (!hasQuestion2()) {
          return false;
        }
        if (!hasQuestion3()) {
          return false;
        }
        if (!hasEncryptedKey1()) {
          return false;
        }
        if (!hasEncryptedKey2()) {
          return false;
        }
        if (!hasEncryptedKey3()) {
          return false;
        }
        if (!hasEncryptedContent()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ThreeQuestionsTxtFileMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ThreeQuestionsTxtFileMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object question1_ = "";
      /**
       * <code>required string question1 = 1;</code>
       * @return Whether the question1 field is set.
       */
      public boolean hasQuestion1() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string question1 = 1;</code>
       * @return The question1.
       */
      public String getQuestion1() {
        Object ref = question1_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            question1_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string question1 = 1;</code>
       * @return The bytes for question1.
       */
      public com.google.protobuf.ByteString
          getQuestion1Bytes() {
        Object ref = question1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          question1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string question1 = 1;</code>
       * @param value The question1 to set.
       * @return This builder for chaining.
       */
      public Builder setQuestion1(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        question1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string question1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuestion1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        question1_ = getDefaultInstance().getQuestion1();
        onChanged();
        return this;
      }
      /**
       * <code>required string question1 = 1;</code>
       * @param value The bytes for question1 to set.
       * @return This builder for chaining.
       */
      public Builder setQuestion1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        question1_ = value;
        onChanged();
        return this;
      }

      private Object question2_ = "";
      /**
       * <code>required string question2 = 2;</code>
       * @return Whether the question2 field is set.
       */
      public boolean hasQuestion2() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string question2 = 2;</code>
       * @return The question2.
       */
      public String getQuestion2() {
        Object ref = question2_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            question2_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string question2 = 2;</code>
       * @return The bytes for question2.
       */
      public com.google.protobuf.ByteString
          getQuestion2Bytes() {
        Object ref = question2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          question2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string question2 = 2;</code>
       * @param value The question2 to set.
       * @return This builder for chaining.
       */
      public Builder setQuestion2(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        question2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string question2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuestion2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        question2_ = getDefaultInstance().getQuestion2();
        onChanged();
        return this;
      }
      /**
       * <code>required string question2 = 2;</code>
       * @param value The bytes for question2 to set.
       * @return This builder for chaining.
       */
      public Builder setQuestion2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        question2_ = value;
        onChanged();
        return this;
      }

      private Object question3_ = "";
      /**
       * <code>required string question3 = 3;</code>
       * @return Whether the question3 field is set.
       */
      public boolean hasQuestion3() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string question3 = 3;</code>
       * @return The question3.
       */
      public String getQuestion3() {
        Object ref = question3_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            question3_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string question3 = 3;</code>
       * @return The bytes for question3.
       */
      public com.google.protobuf.ByteString
          getQuestion3Bytes() {
        Object ref = question3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          question3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string question3 = 3;</code>
       * @param value The question3 to set.
       * @return This builder for chaining.
       */
      public Builder setQuestion3(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        question3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string question3 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuestion3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        question3_ = getDefaultInstance().getQuestion3();
        onChanged();
        return this;
      }
      /**
       * <code>required string question3 = 3;</code>
       * @param value The bytes for question3 to set.
       * @return This builder for chaining.
       */
      public Builder setQuestion3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        question3_ = value;
        onChanged();
        return this;
      }

      private Object encryptedKey1_ = "";
      /**
       * <code>required string encryptedKey1 = 4;</code>
       * @return Whether the encryptedKey1 field is set.
       */
      public boolean hasEncryptedKey1() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string encryptedKey1 = 4;</code>
       * @return The encryptedKey1.
       */
      public String getEncryptedKey1() {
        Object ref = encryptedKey1_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            encryptedKey1_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string encryptedKey1 = 4;</code>
       * @return The bytes for encryptedKey1.
       */
      public com.google.protobuf.ByteString
          getEncryptedKey1Bytes() {
        Object ref = encryptedKey1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          encryptedKey1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string encryptedKey1 = 4;</code>
       * @param value The encryptedKey1 to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedKey1(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        encryptedKey1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string encryptedKey1 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptedKey1() {
        bitField0_ = (bitField0_ & ~0x00000008);
        encryptedKey1_ = getDefaultInstance().getEncryptedKey1();
        onChanged();
        return this;
      }
      /**
       * <code>required string encryptedKey1 = 4;</code>
       * @param value The bytes for encryptedKey1 to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedKey1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        encryptedKey1_ = value;
        onChanged();
        return this;
      }

      private Object encryptedKey2_ = "";
      /**
       * <code>required string encryptedKey2 = 5;</code>
       * @return Whether the encryptedKey2 field is set.
       */
      public boolean hasEncryptedKey2() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string encryptedKey2 = 5;</code>
       * @return The encryptedKey2.
       */
      public String getEncryptedKey2() {
        Object ref = encryptedKey2_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            encryptedKey2_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string encryptedKey2 = 5;</code>
       * @return The bytes for encryptedKey2.
       */
      public com.google.protobuf.ByteString
          getEncryptedKey2Bytes() {
        Object ref = encryptedKey2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          encryptedKey2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string encryptedKey2 = 5;</code>
       * @param value The encryptedKey2 to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedKey2(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        encryptedKey2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string encryptedKey2 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptedKey2() {
        bitField0_ = (bitField0_ & ~0x00000010);
        encryptedKey2_ = getDefaultInstance().getEncryptedKey2();
        onChanged();
        return this;
      }
      /**
       * <code>required string encryptedKey2 = 5;</code>
       * @param value The bytes for encryptedKey2 to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedKey2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        encryptedKey2_ = value;
        onChanged();
        return this;
      }

      private Object encryptedKey3_ = "";
      /**
       * <code>required string encryptedKey3 = 6;</code>
       * @return Whether the encryptedKey3 field is set.
       */
      public boolean hasEncryptedKey3() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required string encryptedKey3 = 6;</code>
       * @return The encryptedKey3.
       */
      public String getEncryptedKey3() {
        Object ref = encryptedKey3_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            encryptedKey3_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string encryptedKey3 = 6;</code>
       * @return The bytes for encryptedKey3.
       */
      public com.google.protobuf.ByteString
          getEncryptedKey3Bytes() {
        Object ref = encryptedKey3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          encryptedKey3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string encryptedKey3 = 6;</code>
       * @param value The encryptedKey3 to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedKey3(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        encryptedKey3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string encryptedKey3 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptedKey3() {
        bitField0_ = (bitField0_ & ~0x00000020);
        encryptedKey3_ = getDefaultInstance().getEncryptedKey3();
        onChanged();
        return this;
      }
      /**
       * <code>required string encryptedKey3 = 6;</code>
       * @param value The bytes for encryptedKey3 to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedKey3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        encryptedKey3_ = value;
        onChanged();
        return this;
      }

      private Object encryptedContent_ = "";
      /**
       * <code>required string encryptedContent = 7;</code>
       * @return Whether the encryptedContent field is set.
       */
      public boolean hasEncryptedContent() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required string encryptedContent = 7;</code>
       * @return The encryptedContent.
       */
      public String getEncryptedContent() {
        Object ref = encryptedContent_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            encryptedContent_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string encryptedContent = 7;</code>
       * @return The bytes for encryptedContent.
       */
      public com.google.protobuf.ByteString
          getEncryptedContentBytes() {
        Object ref = encryptedContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          encryptedContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string encryptedContent = 7;</code>
       * @param value The encryptedContent to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        encryptedContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string encryptedContent = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncryptedContent() {
        bitField0_ = (bitField0_ & ~0x00000040);
        encryptedContent_ = getDefaultInstance().getEncryptedContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string encryptedContent = 7;</code>
       * @param value The bytes for encryptedContent to set.
       * @return This builder for chaining.
       */
      public Builder setEncryptedContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        encryptedContent_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ThreeQuestionsTxtFileMsg)
    }

    // @@protoc_insertion_point(class_scope:ThreeQuestionsTxtFileMsg)
    private static final ThreeQuestionsTxtFileMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ThreeQuestionsTxtFileMsg();
    }

    public static ThreeQuestionsTxtFileMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ThreeQuestionsTxtFileMsg>
        PARSER = new com.google.protobuf.AbstractParser<ThreeQuestionsTxtFileMsg>() {
      @Override
      public ThreeQuestionsTxtFileMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ThreeQuestionsTxtFileMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ThreeQuestionsTxtFileMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ThreeQuestionsTxtFileMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public ThreeQuestionsTxtFileMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ThreeQuestionsTxtFileMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ThreeQuestionsTxtFileMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036ThreeQuestionsTxtFileMsg.proto\"\262\001\n\030Thr" +
      "eeQuestionsTxtFileMsg\022\021\n\tquestion1\030\001 \002(\t" +
      "\022\021\n\tquestion2\030\002 \002(\t\022\021\n\tquestion3\030\003 \002(\t\022\025" +
      "\n\rencryptedKey1\030\004 \002(\t\022\025\n\rencryptedKey2\030\005" +
      " \002(\t\022\025\n\rencryptedKey3\030\006 \002(\t\022\030\n\020encrypted" +
      "Content\030\007 \002(\tB\035B\033ThreeQuestionsTxtFilePr" +
      "otos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ThreeQuestionsTxtFileMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ThreeQuestionsTxtFileMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ThreeQuestionsTxtFileMsg_descriptor,
        new String[] { "Question1", "Question2", "Question3", "EncryptedKey1", "EncryptedKey2", "EncryptedKey3", "EncryptedContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
